# Vector and Matrix manipulation in Python

## Basic vectors:

In [0]:
# vectors in python:
u = [2, 13]
v = [4, 5]

print(u, v)

[2, 13] [4, 5]


In [0]:
# numpy library has some handy operations for vectors and matrices:

import numpy as np
u = np.asarray(u)
v = np.asarray(v)

print("u =", u)
print("v =", v)

# dot product - or element-wise multiplication
w = v.dot(u)
print("w =", w)

test = v[0]*u[0] + v[1]*u[1]
print("test =", test)

u = [ 2 13]
v = [4 5]
w = 73
test = 73


## Basic matrices:

In [0]:
# How to write matrices?
M = [
     [1,2],
     [3,4]
    ]
M = np.asarray(M)

print("M =", M)
print("M transposed =", M.T)

M = [[1 2]
 [3 4]]
M transposed = [[1 3]
 [2 4]]


In [0]:
# multiply by real number

a = 10
print("a*M =", a*M)

a*M = [[10 20]
 [30 40]]


In [0]:
# add / subtract ...

print("M+M =", M+M)
print("M-M =", M-M)

M+M = [[2 4]
 [6 8]]
M-M = [[0 0]
 [0 0]]


In [0]:
# How to multiply them?

A = [
     [1,0,-3],
     [-2,4,1]
    ]
B = [
     [1,0,4],
     [-2,3,-1],
     [0,-1,2]
    ]
A = np.asarray(A)
B = np.asarray(B)

print("A:", A)
print("B:", B)
C = np.matmul(A, B)

print("C = AB = ", C)

A: [[ 1  0 -3]
 [-2  4  1]]
B: [[ 1  0  4]
 [-2  3 -1]
 [ 0 -1  2]]
C = AB =  [[  1   3  -2]
 [-10  11 -10]]


### ... and not so basic matrices ...

In [0]:
# So ... if A*B = C
# can we get an inverse element?
#                 C * B_inverse => A ?

# Let's plug in some linear algebra:
# inverse!
invB = np.linalg.inv(B) 
print("inverse of B:", invB)

# C * B_inverse => A
Areconstruct = np.matmul(C, invB)
print("Reconstructed A:", Areconstruct)
print("Original A:", A)

inverse of B: [[ 0.38461538 -0.30769231 -0.92307692]
 [ 0.30769231  0.15384615 -0.53846154]
 [ 0.15384615  0.07692308  0.23076923]]
Reconstructed A: [[ 1.00000000e+00 -1.66533454e-16 -3.00000000e+00]
 [-2.00000000e+00  4.00000000e+00  1.00000000e+00]]
Original A: [[ 1  0 -3]
 [-2  4  1]]


# Today's tasks:

## Task 1: Vector normalization

Given a vector u = (10,2,3) ... find me a normalized u (an unit vector of u).

In [5]:
import numpy as np
u = [10,2,3]
u = np.asarray(u)

# we will need to calculate it's lenght (magnitude)
# |u| = ??? (if need be, find it in the slides...)
import math
u_dist = math.sqrt(u[0]^2 + u[1]^2 + u[2]^2)
print(u_dist)


# and then use this formula:
# u / |u| = normalized u

u_norm = u / u_dist
print(u_norm)

3.0
[3.33333333 0.66666667 1.        ]


In [12]:
import math 

# bonus, write them as functions:
def vector_magnitude(u):
    # returns magnitude of the vector u
    cummulative = 0
    for val in u:
        cummulative += val*val

    return math.sqrt(cummulative)
    
def vector_normalization(u):
    # returns unit vector of the vector u
    dist = vector_magnitude(u)
    return u / dist

# then we should be able to check:
u = np.asarray([10,2,3])

# PS: this is not precise:
#assert vector_magnitude(vector_normalization(u)) == 1.0 # ... that the magnitude of a normalized vector is 1.0

print(u)
print(vector_normalization(u))
print(vector_magnitude(vector_normalization(u)))

# This number is very close to 1.0, but we lost some precision in the process
print(1.0 - vector_magnitude(vector_normalization(u)))

# Let's instead check if the error is small enough!
epsilon = 0.00001
assert (1.0 - vector_magnitude(vector_normalization(u))) < epsilon

[10  2  3]
[0.94072087 0.18814417 0.28221626]
0.9999999999999999
1.1102230246251565e-16


## Task 2: Interpolation between vectors

Vector interpolation:

<p align="center">
<img src="https://raw.githubusercontent.com/previtus/cci_data_maths_methods/master/week11_vectors-matrices/w11_vectors-interpolation-ilustration.png" width="520">
</p>



Given vectors u and v, write a function which will give me a linear combination of these vectors (aka will return the mixed vector m).

In [0]:
def vector_interpolation(u, v, a):
    # u is a vector
    # v is a vector
    # a is a real number between 0 and 1
    assert a >= 0.0 # maybe too hash way of checking - we could otherwise print out a message ... this kills the code directly!
    assert a <= 1.0
    
    m = a*u + (1.0-a)*v
    return m

Bonus, let's use that function!

*PS: this piece of code will need the function to be doing what's it supposed to ...*


In [14]:
# encoded RGB colors
color_1 = [255,0,0]
color_2 = [0,0,255]
color_1 = np.asarray(color_1)
color_2 = np.asarray(color_2)

# plot it as a strip of colors:
import numpy as np
import IPython.display
import PIL.Image
samples_x = 800
height = 20
pixels_per_sample = 1

size = [height, samples_x*pixels_per_sample, 3]
empty_image = np.zeros(size)

for i in range(samples_x):
    block = [i*pixels_per_sample, (i+1)*pixels_per_sample]
    a = float(i) / (samples_x-1) # goes from 0.0 to 1.0
    
    # << This will call your interpolation function "vector_interpolation"
    color = vector_interpolation(color_1, color_2, a)

    empty_image[0:height, block[0]:block[1], :] = color

IPython.display.display(PIL.Image.fromarray(np.uint8(empty_image)))